const GET_ALL_USERS = {
  START: "GET_ALL_USERS_START",
  SUCCESS: "GET_ALL_USERS_SUCCESS",
  FAIL: "GET_ALL_USERS_FAIL",
};

const GET_USER_BY_ID = {
  START: "GET_USER_BY_ID_START",
  SUCCESS: "GET_USER_BY_ID_SUCCESS",
  FAIL: "GET_USER_BY_ID_FAIL",
};

const LOGIN_USER = {
  SUCCESS: "LOGIN_SUCCESS",
};

const LOGOUT_USER = "LOGOUT_SUCCESS";

export { GET_ALL_USERS, GET_USER_BY_ID, LOGIN_USER, LOGOUT_USER };
